### ISSUE TITLE
Version 2.0.0 on Splunkbase seems to be broken?

### ISSUE THREAD

**Issue by DH-Mike** [rapid7/icon-splunk-app#24]
Hi!
I updated to the newest version of this plugin as a troubleshooting step, it seems that [Version 2.0.0 on SplunkBase](https://splunkbase.splunk.com/app/4673/#/details) is broken..

Here's the error I get:
```
02-10-2021 12:06:31.771 +0100 INFO  sendmodalert - Invoking modular alert action=send_to_insightconnect for search="Insightconnect Test Alert" sid="rt_scheduler_bWljaGFlbC5zdHJvdXQ__search__RMD5dd72cb9f8907ef09_at_1612954802_10048.1" in app="search" owner="test.user" type="saved"
02-10-2021 12:06:31.786 +0100 ERROR sendmodalert - action=send_to_insightconnect STDERR -  Traceback (most recent call last):
02-10-2021 12:06:31.786 +0100 ERROR sendmodalert - action=send_to_insightconnect STDERR -    File "/opt/splunk/etc/apps/rapid7_insightconnect/bin/send_to_insightconnect.py", line 4, in <module>
02-10-2021 12:06:31.786 +0100 ERROR sendmodalert - action=send_to_insightconnect STDERR -      import ta_rapid7_insightconnect_declare
02-10-2021 12:06:31.786 +0100 ERROR sendmodalert - action=send_to_insightconnect STDERR -  ImportError: No module named ta_rapid7_insightconnect_declare
02-10-2021 12:06:31.788 +0100 WARN  sendmodalert - action=send_to_insightconnect - Alert action script returned error code=1
02-10-2021 12:06:31.788 +0100 INFO  sendmodalert - action=send_to_insightconnect - Alert action script completed in duration=15 ms with exit code=1
```

**Comment by itsmohitnarayan** [comment]
@DH-Mike 
You can check if it's installed using pip or another package manager.
-pip show ta_rapid7_insightconnect_declare
Ensure that the Python interpreter running the script can locate the module.
Verify that the import statement in "send_to_insightconnect.py" is correct.
-import ta_rapid7_insightconnect_declare
If the module is not in a standard location, you can modify the Python path (sys.path) within your script to include the directory where the module is located. Add the following lines at the beginning of your script
-import sys
sys.path.append("/path/to/ta_rapid7_insightconnect_declare")
Replace "/path/to/ta_rapid7_insightconnect_declare" with the actual path to the module.
If the module is not installed, you can install it using pip
-pip install ta_rapid7_insightconnect_declare
Make sure you are using the correct version of the module that is compatible with your script.
After following these steps, run your script again and check if the ImportError is resolved.

**Comment by dlaverty-r7** [comment]
Closing out for now as archiving this repo.
